#vi configmapsecrets.yaml
apiVersion: v1
kind: Pod
metadata:
  name: mypodapp
spec:
  containers:
  - name: mypodapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - name: config-dir
        mountPath: /etc/config
    ports:
      - containerPort: 80
  volumes:
    - name: config-dir
      ConfigMap:
        name: bb-configmap
#kubectl apply -f configmapsecrets.yaml